<?php

use App\Service\Fs\File;
use App\Service\Fs\Folder;

/** @var Folder[] $folders */
$folders = $this->items['folders'];

/** @var File[] $files */
$files = $this->items['files'];
?>
<?php if (count($folders)) : ?>
  <div class="mt-4">
    <div class="row gx-3 d-flex align-items-stretch">
      <?php foreach ($folders as $folder) : ?>
        <div class="col-2 mb-3">
          <?php echo $this->partial('index/folder', ['folder' => $folder]); ?>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
<?php endif; ?>
<?php if (count($files)) : ?>
  <div class="mt-4">
    <div class="row gx-3 d-flex align-items-stretch">
      <?php foreach ($files as $file) : ?>
        <div class="col-2 mb-3">
          <?php echo $this->partial('index/file', ['file' => $file]); ?>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
<?php endif; ?>