<div class="dropdown">
  <a class="btn btn-primary dropdown-toggle px-3"
     role="button"
     data-mdb-dropdown-init
     data-mdb-ripple-init>
    <i class="fas fa-plus"></i> Create
  </a>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <li>
      <a class="dropdown-item" role="button" onclick="createFolder()">
        <i class="fas fa-folder me-1"></i> Folder
      </a>
    </li>
    <li>
      <a class="dropdown-item" role="button" onclick="uploadFromComputer()">
        <i class="fas fa-desktop me-1"></i> From computer
      </a>
    </li>
    <li>
      <a class="dropdown-item" role="button" onclick="uploadByUrl()">
        <i class="fas fa-link me-1"></i> By URL
      </a>
    </li>
  </ul>
</div>